name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        type: [vim, neovim]
        version: [stable, nightly]
        include:
          - type: vim
            version: v8.0.0000
          - type: vim
            version: v8.1.0000
          - type: vim
            version: v8.2.0000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.type == 'neovim' }}
      - name: Run test
        run: cd ./test && ./start
